### ISSUE TITLE
cannot install in docker

### ISSUE THREAD

**Issue by lumpov** [genouest/zammad-rocketchat#2]
use https://github.com/zammad/zammad-docker-compose. install inside container yarn, but get error while run:

```
# RAILS_ENV=production rake assets:precompile
(in /opt/zammad)
I, [2020-05-08T19:49:28.980799 #663-47027991922100]  INFO -- : Setting.set('models_searchable', ["Chat::Session", "Organization", "KnowledgeBase::Answer::Translation", "Ticket", "User"])
Yarn executable was not detected in the system.
Download Yarn at https://yarnpkg.com/en/docs/install
# yarn --version
0.32+git
# 
```

**Comment by osallou** [comment]
Hi,
Should rather create issue on zammad side.

Error is not extension specific if you fail to recompiles assets.

Rake not finding yarn though installed is strange.

**Comment by osallou** [comment]
You may as workaround add yarn path to your PATH env var

**Comment by lumpov** [comment]
This will be different instruction for installation of Zammad in docker. https://github.com/zammad/zammad-docker-compose/issues/122 I don't know how to install this add-on in docker.

**Comment by osallou** [comment]
You installed zspm extension asset file via the zammad gui first, right?
Then exec of db and assets commands in docker container?

**Comment by lumpov** [comment]
yes, right.

**Comment by osallou** [comment]
Hum, will try next week and let you know.

Maybe a change in zammad docker images vs time i created the extension.

Zammad extensions are not documented, and they may have modified something.

**Comment by osallou** [comment]
Hi @lumpov 
I did a test and it worked fine as per instructed (at least rocketchat menu appears in menu), with image zammad/zammad-docker-compose:zammad-3.3.0-19

Steps after zammad is up and running:

* in config menu/packages, I installed zammad-rocketchat.szpm package
* connected to zammad-railsserver container
* edited db/seeds.rb to add *rocket* to seeds variable
* ran commands:

    docker exec -it 90589376343c /bin/bash (90589376343c is my railsserver container)
    
    root@90589376343c:/opt/zammad# RAILS_ENV=production rake db:seed
    
    I, [2020-05-10T06:49:39.589953 #424-46938705315260]  INFO -- : Setting.set('models_searchable', ["Chat::Session", "Ticket", "User", "Organization", "KnowledgeBase::Answer::Translation"])
    I, [2020-05-10T06:49:40.017009 #424-46938705315260]  INFO -- : Enqueued SearchIndexJob (Job ID: dc735fbe-099c-4642-ab15-343006f97b7e) to DelayedJob(default) with arguments: "User", 2
    I, [2020-05-10T06:49:40.019831 #424-46938705315260]  INFO -- : Enqueued SearchIndexAssociationsJob (Job ID: 14dd734c-2cd9-4ea4-9ad6-2dd7ddb31089) to DelayedJob(default) with arguments: "User", 2
    
    root@90589376343c:/opt/zammad# RAILS_ENV=production rake assets:precompile
    I, [2020-05-10T06:50:04.237300 #429-46977965016500]  INFO -- : Setting.set('models_searchable', ["Chat::Session", "Ticket", "User", "Organization", "KnowledgeBase::Answer::Translation"])
    Yarn executable was not detected in the system.
    Download Yarn at https://yarnpkg.com/en/docs/install
    I, [2020-05-10T06:50:30.627019 #429-46977965016500]  INFO -- : Writing /opt/zammad/public/assets/application-a52f95bc7f3239ae02f83b81f016625c5c203896ea87a186d3df1580dfa124b7.js
    I, [2020-05-10T06:50:30.627370 #429-46977965016500]  INFO -- : Writing /opt/zammad/public/assets/application-a52f95bc7f3239ae02f83b81f016625c5c203896ea87a186d3df1580dfa124b7.js.gz


* Restarted containers rails-server, nginx and zammad-scheduler

After that, rocketchat menu appears in config/integrations as expected and needs to be configured

**Comment by lumpov** [comment]
thank you for support, I did it myself.

I expect that this add-on implement new channel, but it is only do notifications like Slack integration.

I'm looking for new channel add-on...

**Comment by osallou** [comment]
to do so, you need in fact a "plugin" on rocketchat side, listening to messages and using zammad API to create new tickets based on rocket message.

**Comment by lumpov** [comment]
It's not a problem, but it is not enough, becouse I would like to choice by hand this channel in Zammad UI.
